/* 
 * We employ this define/wizardry to allow us to include the #define'd 
 * types from the y.tab.h file generated by the parser.
 */

#ifndef __TYPEDEFS_HPP__
#define __TYPEDEFS_HPP__
/* TODO Insert Ascii trollface */
#define YYSTYPE int
#include "../y.tab.h"
#undef YYSTYPE
#endif



